.github/workflows/build.yml, .github/workflows/unit_tests.yml
https://app.dework.xyz/nation3/develop-1?taskId=d77d0caa-669a-4fea-a5c1-247625bba930
closes #2
=> chore: enable ci - build

.github/codecov.yml, .github/workflows/unit_tests.yml
https://app.dework.xyz/nation3/develop-1?taskId=b172bc47-12e8-47a7-8341-259ff61e111f
closes #4
=> test: enable code coverage (#4)

contracts/N3BI.sol, package-lock.json, package.json, test/N3BI.ts
=> Setup basic build infrastructure (#11)

ui/components/Layout.tsx, ui/lib/config.ts
Same as https://github.com/nation3/app/pull/127
=> refactor: add etherscan domain to config

hardhat/contracts/N3BI.sol, hardhat/contracts/mock/Nation3GenesisPassportMock.sol, hardhat/scripts/deploy-n3bi.ts, hardhat/test/N3BI.ts
=> feat: check if the account holds a passport nft (#88)

README.md, hardhat/contracts/N3BI.sol, hardhat/contracts/mock/NationCredMock.sol, hardhat/contracts/mock/PassportMock.sol, hardhat/contracts/nationcred/INationCred.sol, hardhat/scripts/deploy-n3bi.ts, hardhat/test/N3BI.ts
Use NationCred contract to check if a citizen is active
closes #90
=> feat: use nationcred contract (#90)

README.md
Add link to the Nation3 Basic Income research summary.
=> docs: add research summary

hardhat/README.md, hardhat/contracts/N3BI.sol, hardhat/package-lock.json, hardhat/package.json, hardhat/scripts/deploy-n3bi.ts, hardhat/test/N3BI.ts
🉑 登録
close #101
https://goerli.etherscan.io/address/0x036DA579A50ac81bE90A74421b4f9fAc5415Fa36#code
=> Implement enrollment (#101)

ui/src/pages/index.tsx
=> fix: build error (#108)

hardhat/.solhint.json, hardhat/contracts/BasicIncomeDistributor.sol, hardhat/contracts/governance/IVotingEscrow.sol, hardhat/contracts/mock/NationCredMock.sol, hardhat/contracts/mock/PassportIssuerMock.sol, hardhat/contracts/mock/PassportMock.sol, hardhat/contracts/mock/PassportUtilsMock.sol, hardhat/contracts/mock/VotingEscrowMock.sol, hardhat/contracts/passport/IPassportIssuer.sol, hardhat/hardhat.config.ts
=> fix: upgraded to Solidity 0.8.26

hardhat/package-lock.json
=> fix: build error

hardhat/package-lock.json, hardhat/package.json
=> 🧹 chore: upgrade dependencies

hardhat/package-lock.json, hardhat/package.json, hardhat/scripts/deploy-distributor.ts
=> 🧹 chore: remove hardhat-etherscan

.github/codecov.yml, .github/workflows/hardhat_unit_tests.yml, hardhat/README.md
=> ✅ test: adjust coverage threshold

hardhat/package-lock.json, hardhat/package.json
=> 🧹 chore: remove ethers-v5

hardhat/package-lock.json, hardhat/package.json
=> 🧹 chore: remove @types/mocha

hardhat/contracts/BasicIncomeDistributor.sol
=> 🍝 refactor: remove `latestClaimTimestamps`

hardhat/contracts/BasicIncomeDistributor.sol, hardhat/scripts/deploy-distributor.ts, hardhat/test/BasicIncomeDistributor.ts
A dework bounty for making small fix on the constructor
[](https://github.com/nation3/n3bi/issues/124)
=> Added contract owner to contructor param

.github/codecov.yml, .github/workflows/hardhat_unit_tests.yml, hardhat/README.md
=> 📔 coverage: increase to 91.95%

hardhat/contracts/BasicIncomeDistributor.sol, hardhat/test/BasicIncomeDistributor.ts
Add NotEnrolledError and update the test file.
https://github.com/nation3/n3bi/issues/125
=> Add NotEnrolledError

.github/workflows/hardhat_build.yml, .github/workflows/hardhat_linters.yml, .github/workflows/hardhat_unit_tests.yml, .github/workflows/ui_ci.yml, hardhat/package.json, ui/package.json
=> ⚙️ chore: set node 20.x
